### ISSUE TITLE
key_management_settings error in 1.40.19

### ISSUE THREAD

**Issue by lolsborn** [BerriAI/liteLLM-proxy#12]
Seeing the following stack trace in 1.40.19
```
Traceback (most recent call last):
  File "/opt/casemark/litellm/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/opt/casemark/litellm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/casemark/litellm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/casemark/litellm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/casemark/litellm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/casemark/litellm/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 498, in run_server
    if key_management_settings is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'key_management_settings' where it is not associated with a value
```
Looking at the code it kind of makes sense that this would error,
Line 498 is trying to access key_management_settings, but it's undefined here based on the indention level.
Even though key_management_system is defined on 472 in scope at 498

I would create a PR, but I'm not sure what the intention is here 
![image](https://github.com/BerriAI/liteLLM-proxy/assets/60548/14bfaabd-8f40-4e2b-8722-8efa5d3b8a64)

**Comment by lolsborn** [comment]
Posted this in the wrong repo.  Appears to be resolved https://github.com/BerriAI/litellm/issues/4324
