### ISSUE TITLE
ModuleNotFoundError: No module named 'openai.error'

### ISSUE THREAD

**Issue by chrisyuuuuu** [BerriAI/liteLLM-proxy#13]
$ python main.py 
Python-dotenv could not parse statement starting at line 1
Traceback (most recent call last):
  File "/Users/icourt/PythonProjects/liteLLM-proxy-main/main.py", line 8, in <module>
    import llm as llm
  File "/Users/icourt/PythonProjects/liteLLM-proxy-main/llm.py", line 10, in <module>
    import openai.error
ModuleNotFoundError: No module named 'openai.error'
(litellm-proxy-main-3.11)

**Comment by yixuantt** [comment]
same issue.
