### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by gururise** [BerriAI/liteLLM-proxy#3]
No matter what I do, I get an 401 Unauthorized response back.

I tried using the .env and setting up my OpenAI key.
I tried using Bearer Auth header with my OpenAI key.

Here is the json body I'm sending via PostMan:
```
{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "content": "Hello, whats the weather in San Francisco??",
      "role": "user"
    }
  ]
}
```

I've also tried accessing TogtherAI models and am having the same problem.
Using the latest git version.

**Comment by krrishdholakia** [comment]
Hey @gururise, 

The key needed to pass in via bearer is the user key -

see user_key_auth: https://github.com/BerriAI/liteLLM-proxy/blob/bbe0f62e3a413c184607a188ec1b9ca931fef040/main.py#L65C63-L65C63

it checks if the user key is valid here - https://github.com/BerriAI/liteLLM-proxy/blob/bbe0f62e3a413c184607a188ec1b9ca931fef040/main.py#L32

You can create a user key by calling /key/new: 
https://github.com/BerriAI/liteLLM-proxy/blob/bbe0f62e3a413c184607a188ec1b9ca931fef040/main.py#L104


--
We're assuming you have your api keys in the .env and trying to provide users access to this.

**Comment by krrishdholakia** [comment]
Let me know if that works for you. Happy to hop on a call and help debug as well.

**Comment by gururise** [comment]
> Hey @gururise,
> 
> The key needed to pass in via bearer is the user key -
> 
> see user_key_auth: https://github.com/BerriAI/liteLLM-proxy/blob/bbe0f62e3a413c184607a188ec1b9ca931fef040/main.py#L65C63-L65C63
> 
> it checks if the user key is valid here -
> 
> https://github.com/BerriAI/liteLLM-proxy/blob/bbe0f62e3a413c184607a188ec1b9ca931fef040/main.py#L32
> 
> You can create a user key by calling /key/new:
> 
> https://github.com/BerriAI/liteLLM-proxy/blob/bbe0f62e3a413c184607a188ec1b9ca931fef040/main.py#L104
> 
> -- We're assuming you have your api keys in the .env and trying to provide users access to this.

I must still be doing something wrong. I set the environment variable USERS_KEYS="abcd,efgh"

Then I hit the /key/new endpoint and end up with this error:
```
liteLLM-proxy on  main [$!?] is 📦 v0.0.1 via 🐍 v3.11.5 (venv) took 38s 
❯ export USERS_KEYS="abcd,efgh"

liteLLM-proxy on  main [$!?] is 📦 v0.0.1 via 🐍 v3.11.5 (venv) took 4s 
❯ python main.py
INFO:     Started server process [1003699]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
abcd
abcd,efgh
INFO:     127.0.0.1:35372 - "POST /key/new HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gene/Downloads/liteLLM-proxy/venv/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gene/Downloads/liteLLM-proxy/main.py", line 111, in generate_key
    total_budget = data["total_budget"]
                   ~~~~^^^^^^^^^^^^^^^^
KeyError: 'total_budget'
```

**Comment by gururise** [comment]
Is there a way to not require a userkey?

**Comment by krrishdholakia** [comment]
Yea just comment out this dependencies line - https://github.com/BerriAI/liteLLM-proxy/blob/bbe0f62e3a413c184607a188ec1b9ca931fef040/main.py#L65

**Comment by krrishdholakia** [comment]
hmm how do plan on giving users access to your models if you remove this? @gururise

**Comment by gururise** [comment]
> hmm how do plan on giving users access to your api keys if you remove this? @gururise

What I meant is, I would like to pre-define a user-key (in the env file) that could be used and never changes upon app restarts.

**Comment by krrishdholakia** [comment]
Oh - then just modify this line to be the key in your .env 

Are you setting budget limits etc. on this key?

**Comment by gururise** [comment]
> Oh - then just modify this line to be the key in your .env
> 
> Are you setting budget limits etc. on this key?

No budget limits. Just want unlimited usage.

**Comment by krrishdholakia** [comment]
oh yea that 1 line change should solve your problem. Curious - what're you using the proxy for?
